apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: applications
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: applications
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/my-apps/app-2
    repoURL: https://github.com/ch-stark/app-of-app-quickstart.git
    targetRevision: HEAD
